app/routes/storage.js
app/services/files.js
app/services/folder.js
app/services/index.js

- FIX: On multiple folder move, rebuildHierarchy breaks ancestors model PRIMARY constraint. As readed on the sequelize-hierarchy docs, when parentId fodler are updated via sequelize, an inline hierarchy hook is already fired. 
TODO: Fix overwrite repetitions on same folder name.

Remove uneeded rebuildHierarchy call that breaks folder model ancestors

---

infrastructure/docker-compose.yml
infrastructure/volumes/dbeaver_logs/.gitignore
infrastructure/volumes/dbeaver_workspace/.gitignore

Every time we bring the infrastructure up the connection to the DB has to be configured on cloudbeaver. By mounting the volumes we'll have it persistent across risings.

[_]: feature/persist-cloudbeaver-config

---

src/app/routes/teams.js

- Adds `bridgeUser` field to `user` to create to prevent field to be empty
- Prevents `bridgeUser` to remain null when this field should be set properly

[_]:fix/store-bridge-user-on-teams-admin-creation

---

infrastructure/docker-compose.yml

Previously it was referring to production Dockerfile now referring to development Dockerfile

[_]: fix/refer to the development Dockerfile in bridge

---

migrations/20220309190600-create-deleted-files-trigger.js

Updated `insert_deleted_files` to return the 'old' value.
Previously the deletion was aborted due the trigger returning the 'new' value which on DELETE triggers is null.
In order to test it you will need a fresh database to run the migrations in to it.

[_]: fix/delete folders correctly

---

src/app/services/backups.js

Previously, making a get request to /api/backup/device was returning an internal error code with the following message:
``` json
{
"error": "column reference \"id\" is ambiguous"
}
```
This was happening because the query executed had a _JOIN_ but only on field (id) on the _GROUP BY_:
``` sql
SELECT "device"."id", ...
FROM "devices" AS "device" 
LEFT OUTER JOIN "backups" AS "backups" ON "device"."id" = "backups"."deviceId" 
WHERE "device"."userId" = 1 
GROUP BY "id";``

[_]: fix/ambiguous id reference retriving backup devices

---

.env.template
src/config/initializers/database.ts

- Removes `dialectOptions` since they cause an error connecting in postgres.
Unsure if we want to find the equivalent in postgres (which I couldn't find) or we should just discard this config altogether for postgres. I leave Sergio to take that decision.
- Adds ENV variables to .env file that make it compatible to connect to postgres.

[_]: Fix/maria specific options

---

migrations/20220309190601-create-clear_orphan_folders_by_user-procedure.js
src/app/services/folder.js

On postgres the `clear_orphan_folders_by_user` procedure failed due `query has no destination for result data`. Leaving the leaving folders without a valid parent_id

[_]: fix/ postgres procedure had no destination for result data

---

src/app/routes/storage.ts

Currently when a file is tried to being moved and from some reason fails always returns a 500 Internal Error. But its possible that the error thrown was a `HttpError` with a _custom_ http status. Like in there https://github.com/internxt/drive-server/blob/1f1928119f01cefd23f5709e20d5b3b693db040a/src/app/services/files.js#L228

[_]: fix/ return more specific http status

---

src/app/routes/storage.ts

Don't send the error message when it's an internal error to avoid expose internals

[_]: fix/ hide internal error message

---

src/app/services/user.js

If an error occurs before the _keyserver_ is found or created the transaction gets roll-backed, making it unavailable for the _keyserver_ model. Throwing an error similar to:
`rollback has been called on this transaction(9055cfcd-0249-574d-8b6e-b60ca35c7952), you can no longer use it. (....)`

[_]: Fix/ avoid race conditions on keyserver creation

---

infrastructure/docker-compose.yml

Previously the avatars bucket had to be added manually added. Now it's created alongside the internxt one on the initialize_s3 container

[_]: fix/create avatars bucket on s3 initalization

---

src/app/routes/auth.ts

Catch `FindUserByEmail` promise rejection to properly handle don't find the user email.
The FindUserByEmail function https://github.com/internxt/drive-server/blob/539238d265e0c010d07ab818ff34c21402f2120a/src/app/services/user.js#L174-L193

fix: hadle find user by email promise rejection on access

---

.env.template

Fixed .env.template by renaming RDS_HOSTNAME from 'drive-database' to 'postgres'

[_] fix: Rename rds_hostname on .env.template

---

package.json
src/app/services/folder.js
src/config/initializers/redis.ts

Enable auto pipelining on ioredis to try reduce the latency
> …In order to meet this requirement, the strategy to talk with the N Redis servers to reduce latency is definitely multiplexing (putting the socket in non-blocking mode, send all the commands, and read all the commands later, assuming that the RTT between the client and each instance is similar).
https://redis.io/docs/reference/patterns/distributed-locks/#performance-crash-recovery-and-fsync
Also update ioredis for a fix on autopipeling
https://github.com/luin/ioredis/blob/v4/Changelog.md#4282-2021-12-01

[WT-44] fix: enable auto pipelining on ioredis

---

src/app/services/folder.js

`BIGINT` numbers get converted to string to avoid loss value: https://github.com/sequelize/sequelize/issues/7377#issuecomment-286854849
This was making drive-desktop to never be in sync.
Output of drive-desktop, note that the size is the same but the remote one is a string

[_] fix: return file size as number

---

src/app/services/user.js

- Register returns account already exists instead of returning an internal server error

[_]: fix/register-account-already-exists

---

tests/e2e/e2e-spec.ts

The endpoint must return the _remote_ files with their properties. Not doing so, the desktop app thinks that the files were deleted on _remote_ and deletes it from the _local_ machine of the user. As happened with https://github.com/internxt/drive-server/pull/291
Currently for a file returns:
- id
- created_at
- fileId
- name
- type
- size
- bucket
- folder_id
- encrypt_version
- deleted
- deletedAt
- userId
- modificationTime
- createdAt
- updatedAt
- folderId
Note that the `folder id` appears twice as `folderId` and `folder_id`. Same with `created at`, appears as `created_at` and `createdAt`. 
Also:
- moved helpers method to general e2e description

[_]:test/add-desktop-test

---

src/config/environments/development.js
src/config/environments/staging.js
src/config/environments/test.js
src/config/initializers/server.ts
src/lib/logger.ts

Previously the logger info on the config files was unused. Now if they are present and the environment is not production the "default" development configuration will be overrided by the config

[_]: feat/parametrize-logger-level

---

src/app/services/folder.js

- Fixed 500 error when call `'/storage/tree/:folderId'` endpoint correcting the way that `include` param was set.  
- In the function `getFilesByFolderId`, the `include` param was added inside of `where` param in `Model.file.findAll` function, but it has to go at same level. This fixes a crash that happens when`getFilesByFolderId` is executed when calling the above-mentioned enpoint because the wrong addition of `include` param.
- Code lines affected → 230 to 242
- Documentation: 
- [Sequelize findAll ](https://sequelize.org/api/v6/class/src/model.js~model#static-method-findAll)
Warning! ⚠️ 
- It is necessary to merge this PR before [the related one](https://github.com/internxt/drive-web/pull/510)
Related PRs
- https://github.com/internxt/drive-web/pull/510

[WT-225] bugfix/Add files and folders downlodad using blob in firefox

---

src/app/routes/storage.ts

Noticed on the desktop app that some requests are failing. On the log found that could be because of a timeout.
Changes:
`/storage/v2/folder/:id/` returns an [504 Gateway Timeout](https://developer.mozilla.org/es/docs/Web/HTTP/Status/504) if that is the case

[WT-247] fix: return timeout if database time outs

---

src/app/routes/storage.ts

Noticed on the desktop app that some requests are failing. On the log found that could be because of a timeout.
Changes:
/storage/v2/folder/:id/ returns an [504 Gateway Timeout](https://developer.mozilla.org/es/docs/Web/HTTP/Status/504) if that is the case

[WT-247] fix: return timeout when the database timeouts

---

src/app/services/folder.js

Root trashed files were still retrieved
When drive-desktop is notified that there are changes on the remote simply tries to sync

[_] fix: don't list root trashed files

---

src/app/routes/storage.ts
src/app/services/folder.js

Introduced changes:
- Check if the folder exists explicitly to avoid trying to decrypt a name of an object that is null. 
- Return 400 if the `parentFolderId` does not exist on folder creation.

[_]: fix/check-if-parent-folder-exists-before-creating-folder

---

Dockerfile

These changes aim to solve DNS issues between Alpine Docker images and Kubernetes 1.25. References:
- https://github.com/k3s-io/k3s/issues/6132
The related issues are almost timeouts at the time of asking for domain resolutions to the DNS, in this case, `core-dns`.

fix(cd): use-node-std-instead-of-alpine

---

src/app/services/folder.js

Return the folder plain_name when retrieving the folder tree

[_] chore: add folder plain name on tree request

---

infrastructure/docker-compose.yml

In recent minio versions some policy commands are deprecated, this causes forbidden access errors when starting the s3 storage in the infra since the user is not being created correctly on minio, leading to upload file errors.
Deprecation docs can be found here:
https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-policy.html

[_]: Fix minio user policy init

---

src/app/routes/storage.ts

These changes remove an already deprecated requirement of sending the mnemonic to the backend to rename files.

[_]: fix/remove-mnemonic-from-update-file

---

src/app/routes/storage.ts

- Removed use of GetTreeSize function that not exists
⚠️ Merge first drive-web [PR](https://github.com/internxt/drive-web/pull/707)

[PB-554]: bugfix/Folder download not working correctly in Firefox browser

---

infrastructure/development.Dockerfile

Now when we were trying to run our development environment we were getting the following error:
this PR includes the update of the file infrastructure/development.Dockerfile to work with node version 16.

[_] chore: change node version from 14 to 16 to avoid incompatibility with a dependency

---

src/app/routes/storage.ts
src/app/services/errors/FileWithNameAlreadyExistsError.ts
src/app/services/errors/FolderWithNameAlreadyExistsError.ts
src/app/services/files.js
src/app/services/folder.js

Changed the behavior of the following endpoints so when an update tries to rename an item with an existing name it returns a HTTP status code of `409` instead of `500`
- /storage/folder/{folderId}/meta
- /storage/file/{fileId}/meta

[PB-813] fix: return http code 409 when trying to rename a file with an exists

---

src/app/routes/auth.ts
tests/e2e/e2e-spec.ts

Consumer apps are not able to differentiate between wrong credentials and blocked account by just the http code.
In this PR we change the returned http code so they can take the necessary steps if an account is blocked.
According to RFC, we could also return 404, however, we are already including a message saying the user is blocked, so we have no reason to hide anything.
>    The 403 (Forbidden) status code indicates that the server understood
>    the request but refuses to authorize it.  A server that wishes to
>    make public why the request has been forbidden can describe that
>    reason in the response payload (if any).
> 
>    If authentication credentials were provided in the request, the
>    server considers them insufficient to grant access.  The client
>    SHOULD NOT …

[_]: feat/return 403 instead of 401 when account is blocked

---

src/app/middleware/passport.js
src/app/routes/user.js

1. Moved iat out of `payload` for newTokens to align with drive-server-wip. 
2. Changed older to "future" just to understand better that the token is some time ahead.
3. Added iat to returned  newToken when password changes.

[PB-267]: feat/small changes to add future iat to newTokens

---

src/app/services/files.js

Files with "deleted" status should no be moved nor interacted with. 
This endpoint is used to move files out of trash and between folders, it was ignoring if the file is deleted, so it is able to mark "deleted"  files as "exists" again. 
Then when it reaches this part:
```javascript
if (!file) { // File was found despite STATUS = DELETED so this if is bypassed.
throw Error('File not found');
}
const folderSource = await Model.folder.findOne({ where: { id: file.folder_id, user_id: user.id } });
const folderTarget = await Model.folder.findOne({ where: { id: destination, user_id: user.id } });
if (!folderSource || !folderTarget) {
throw Error('Folder not found');
}
const originalName = App.services.Crypt.decryptName(file.name, file.folder_id);
const destinationName = …
```

[PB-1617]: fix/ select NOT deleted files when trying to move any file

---

.github/workflows/build-and-publish-preview.yaml
.github/workflows/clean-up-pr-preview.yaml
.github/workflows/deploy-pr-preview.yaml
.github/workflows/slash-command-dispatcher.yaml
infrastructure/preview.Dockerfile

These actions would
* build and publish a Docker image with every push to the branch
* add preview label when the PR is ready_for_review (this triggers the app creation)
* clean up the created app whe the PR is closed
* build and publish a Docker image when the PR is merged
* enable slash commands to check and update the created environment
> [!NOTE]
> This PR needs this secrets to be configured in order to work
> - `PAT` - A GitHub Personal Access Token with following scopes `repo:status` `public_repo`.
> - `DOCKERHUB_USERNAME` - The username for the DockerHub account.
> - `DOCKERHUB_TOKEN` - The token for the DockerHub account.
>

[IN-31] ci: add needed actions

---

src/app/routes/gateway.js
src/app/services/backups.js
src/app/services/inxt.js

`updateBucketLimit` was using /gateway/bucket/:id to increase the bucket size limit, nevertheless, that endpoint was deleted 2 years ago in the following PR https://github.com/internxt/bridge/pull/26/files#diff-3fa217d4848a564301c4d296c2f620cd33b296b7c712a1280b90e2af47fbb961L98
Proposed solution is to delete the call to `updateBucketLimit` because is no longer needed.
JIRA: https://inxt.atlassian.net/browse/PB-1921

[PB-1921]: fix/change-network-request-to-update-bucket-limit

---

src/app/services/backups.js

Right now we are detecting if a backups device already exists just by matching the name and bucket, but a device could exists with those matches, and being already deleted. So we need to match an already existing backup devices by this criteria:
- Bucket matches
- Name matches
- Is not deleted
- Is not removed

[_]:(fix) Detect if backups device exists and is not deleted

---

.env.template
src/app/routes/auth.ts
src/app/routes/routes.ts
src/app/services/plan.js
src/app/services/stripe.js
src/app/services/usersReferrals.js

These changes aim to reduce latency on user refresh. The 57% of the time spent on this endpoint this last month has been due to the Stripe external API call, therefore, the change tries to avoid Stripe while guaranteeing consistency on the check done during the refresh that asks Stripe: if a user is a paid one or not.
A new environment variable has been set: `PAYMENTS_SERVER_URL`

[_]: feat/reduce-latency-on-user-refresh

---

src/config/initializers/apn.ts

APN is rejecting requests with `TooManyProviderTokenUpdates`, meaning the JWT is being updated too often. The problem was in the JWT generation logic, where milliseconds were compared with seconds.

[_]: fix: update APN JWT expiration check to use milliseconds

---

src/lib/logger.ts

Add splat() to winston config in order to correctly formar logs in production.

[_]: fix/correctly format logs in prod

---

src/config/initializers/apn.ts
src/config/initializers/server.ts

According to logs it seems the APN connection keeps getting lost forcing a reconnect, pinging it every hour could help avoid disconnects according to APN docs. Also there was a bug where max reconnection attempts were not being reset after a succesfull connection.

[_]: fix/ping apn every hour as suggested by APN docs

---

src/app/routes/auth.ts

- Moved access endpoint log to display correctly the log

[_]: feature/Move access error log

---

src/app/services/backups.js

Bucket is now retrieved directly from activate function on first backup creation

[BR-793] fix: bucket is added to backup folders on first creation

---

src/app/middleware/error-handler.ts

We want to track where are endpoints being called from. We can use headers for this.

[_] chore: added headers log on error
