internxt/drive-server

- app/routes/routes.js
> Change mail to marketing

- app/routes/routes.js
- app/routes/teams.js
- app/services/folder.js
- app/services/keyserver.js
- app/services/photos.js
- app/services/user.js
Now when user deletes the accounts it also deletes the keys
It has not been test
Work in progress
> Delete Account now also deletes keys

- app/routes/stripe.js
- app/services/stripe.js
Added a end point to handle billing portal request
Added a service to get the billing portal url out of stripe
> Stripe billing portal integration

- app/services/stripe.js
> Remove catch for service

- app/routes/payments.js
- app/routes/routes.js
> Token payment

- app/routes/payments.js
Add an error handle if coin market cap call fails
> Added error handler

- app/services/appsumo.js
Adds the exclusive lifetime product.
> Update list of tiers with exclusive lifetime.

- app/services/appsumo.js
Access register incomplete for any lifetime tier.
> Fix RegisterIncompleteLifetime checks.

- config/environments/docker.js
- package.json
> Docker config

- app/services/appsumo.js
Add infinite plan registration.
> Add infinite plan tier

- app/routes/storage.js
- app/services/files.js
- app/services/folder.js
Endpoint to get info of a file with fileId
> Dw2 154 get info file

- app/routes/storage.js
- app/services/stripe.js
This endpoint take the stripe information plan of the user
> Dw2 153 stripe info

- app/routes/storage.js
- app/services/files.js
- app/services/folder.js
> Dw2 155 get recents files

- app/models/share.js
- app/routes/storage.js
- app/services/share.js
- migrations/20210804071033-add-bucket-share.js
- migrations/20210804104524-add-file-token-share.js
- Added _fileToken_ & _bucket_ fields to 'shares' table and their migrations.
- Refactored share service.
- Refactored share endpoints.
> Setup new share service 

- app/models/user.js
- app/services/user.js
- migrations/20210906090001-add_bridge_user_users.js
* New "username" field on user table to represent a unique user identifier. By default, will be filled with the email address.
* New "bridgeUser" field on user table to point the bridge user (network account).
* Former "email" field will be the individual user email address.
> Bridge user field

- src/app/routes/activation.ts
- Restores reset route for sending a deactivation email
> [TICK-201]: fix/restore-reset-route

- src/app/routes/stripe.js
- src/app/services/stripe.js
Allows inxt-clients to retrieve stripe price data given its id
> Retrieve price data given its id

- src/app/routes/gateway.js
Enables checking if a user has completed the registration process.
> Register completed route check

- src/app/services/stripe.js
> Get discounts from a checkout session

- src/app/routes/gateway.js
Enables to lookup via gateway a checkout session
>  Lookup via gateway a checkout session

- src/app/routes/stripe.js
- src/app/services/stripe.js
Some endpoints from Stripe were rotting. On the creation of the SDK I could verify that some of the endpoints were not being used by any project(web, mobile, desktop).
I only cleaned the ones that were not in use without doing any other refactors yet.
> [_]: fix/clean-stripe-endpoints

- src/app/middleware/analytics.ts
- src/app/routes/analytics.js
- src/lib/analytics/Analytics.ts
- src/lib/analytics/AnalyticsService.ts
Identifies actions taken on the Brave browser.
> [_]: feature/brave-sessions-signup-tracking

- src/lib/analytics/AnalyticsService.ts
Adds location to context for brave tracking.
> [_]: fix/await-brave-context

- src/app/routes/stripe.js
- Removes async.waterfall from teams checkout session endpoint
- Reduces complexity introduced in checkout session endpoint
> (fix): Prevents async lib from freezing teams checkout session handler

- src/app/services/mail.js
- src/app/services/stripe.js
- src/config/environments/env.ts
- src/lib/logger.ts
- src/lib/recaptcha.ts
- Centralizes `NODE_ENV` check
- Fixes subscription plans not retrieved properly for team users
> [_]: refactor/centralize-node-env-check

- package.json
- src/app/routes/backup.js
- src/app/services/backups.js
- src/config/initializers/redis.ts
A couple of operations needed to create and fetch folders used as devices in desktop for backups
> [_]: feature/deviceAsFolder

- src/app/routes/stripe.js
- src/app/routes/user.js
- src/app/services/stripe.js
> [DS-11] clean/endpoints

- src/app/routes/share.ts
- src/app/routes/storage.js
- src/app/services/share.js
- Computes folder size using the user id to speed up the process
- Exposes an endpoint for this purpose
- Removes size computation when sharing a folder
> [_]: fix/compute-folder-size-with-user-id

- src/app/routes/auth.ts
- src/app/routes/routes.ts
- tests/controllers/auth.test.ts
Move endpoint to its own controller's file and add basic tests of logic contained on controllers.
> [DS-2] feature/auth-test

- src/app/services/share.js
- Checks if shared directory files had been completely iterated against limit instead of against total count
- Removes unused methods to calculate total counts on a shared directory
> [_]: feat/check-shared-directory-completely-iterated

- src/app/routes/routes.ts
- src/app/routes/storage-v2.ts
- src/app/routes/storage.js
- tests/controllers/storage.test.ts
Moved routes of creating a file and a folder into a new controller handler file to be able to do unit testing on the controller.
> [DS-5] feature/storage-test

- src/app/routes/storage-v2.ts
- src/app/routes/storage.js
- tests/controllers/storage.test.ts
More endpoints from the storage controller are moved to the TS controller and added tests to them.
Mostly related to folders.
> [_]: feature/folder-endpoints

- migrations/20220307180600-increase-encryption-key-size.js
- src/app/services/share.js
We are storing the file encryption key, encrypted. We needed to change the column size and remove the size validation.
> [DW-434] feature/generate-share-file-link-with-code

- migrations/20220413065816-create_mail_limits_table.js
- src/app/models/index.ts
- src/app/models/mailLimit.ts
- src/app/routes/user.js
- src/app/services/user.js
- src/app/services/utils.js
- Provides the functionality for implementing the quota for mails sent to invite a user to Internxt.
> []: feat/mail-limits

- infrastructure/docker-compose.yml
- Removes complex from docker-compose.yml
> [_]: feat/remove-complex

- .github/workflows/code-coverage.yml
- src/app/routes/user.js
- Add proper logging when updating a user error happens.
- Refactor async handler
> [_]: refactor/update-user-logging

- src/app/routes/storage.ts
- src/app/services/folder.js
Exposes two endpoints to get the folder content paginated. (files,folders)
> [_]: feat/get-files-folders-paginated

- src/app/routes/storage.ts
Avoid moving a folder into itself
> [_]: Fix/ refuse move folder into itself

- src/app/routes/auth.ts
- src/app/services/user.js
Return a http status 409 when the email use to register is already registered
> [_]: chore return 409 when email in use

- src/config/environments/sequelize.js
fixes bug on postgres pipeline connection
> [_]: fix(e2e): ssl e2e on postgres

- migrations/20220623125000-create-send-links-tables.js
- migrations/20220624130000-update-shares-table-with-columns.js
- migrations/20220718082248-add-version-to-send-link-item.js
- migrations/20220722090000-add-columns-folders-files.js
Adds missing migrations to drive-server (those that were in wip but not in drive-server);
> [_]: fix(migrations): add missing migrations

- bin/delete-files/index.ts
Migrates script to postgres and adds db port
> [_]: fix(delete-files): migrate script to postgres

- .github/workflows/code-coverage.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/run-tests.yml
- test.txt
Run the test when committing or opening a pr on the branch develop.
Proof:
The test have run 3 times, one for the pr creation and twice for the test commits:
> [WT-62] chore: run test when commit and open pr on develop

- src/app/routes/storage.ts
- Only the authorized user should be allowed to create folders in their namespace
> [WT-88]: Fix/restrict folder creation

- src/app/routes/storage.ts
Make sure backend doesn't return error message
> [WT-93]: Fix/not return error

- src/app/models/index.ts
- src/app/models/thumbnail.ts
- src/app/routes/storage.ts
- src/app/services/files.js
- src/app/services/folder.js
- src/app/services/thumbnails.js
- [WT-102]: Generate thumbnail for .png, .jpeg, .img
- [WT-103]: Send the thumbnail to be uploaded along with the file, on every upload
- [WT-104]: Show the thumbnails when browsing in mosaic
[WT-102]: https://inxt.atlassian.net/browse/WT-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WT-103]: https://inxt.atlassian.net/browse/WT-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WT-104]: https://inxt.atlassian.net/browse/WT-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WT-104]: Feature/thumbnails

- migrations/20221003080000-create-index-folders-bucket.js
- migrations/20221003090000-create-thumbnails-table.js
> [WT-104]: Feature/thumbnails migration

- package.json
- src/lib/analytics/Analytics.ts
- yarn.lock
- Adds rudder analytics
Note: secrets are already set
> [_]: Feat/rudder analytics

- migrations/20221017141638-add-plain-name-to-folder.js
- migrations/20221017141649-add-plain-name-to-file.js
- src/app/models/file.ts
- src/app/models/folder.ts
- src/app/routes/auth.ts
- src/app/routes/storage.ts
- src/app/routes/usersReferrals.js
- src/app/services/files.js
- src/app/services/folder.js
- tests/e2e/e2e-spec.ts
⚠️ Need to add plain_name column to folders and files tables ⚠️ 
- Enables to add plain_name to files and folders in database
> [WT-145] feature/Added plain_name in files and folders

- .github/workflows/deploy-feature.yml
Add action to deploy feature branch
> [_] feat: add deploy feature action

- src/app/services/files.js
- src/app/services/folder.js
- Added deleted filter to query items that are not in trash
> [_]: Feature/add trash filter

- src/app/routes/auth.ts
Errors on the applyUserReferral were not logged
> [WT-209]: fix/catch on referal promise

- src/app/routes/storage.ts
- src/app/services/folder.js
Retrieve only not trashed items by default on `GET storage/tree`
> [_]: Fix/get tree not trashed

- src/app/routes/storage.ts
Reverts internxt/drive-server#348
> Revert "[WT-247] fix: return timeout if database time outs"

- src/app/routes/auth.ts
This change removes the existence of no-expiration tokens. 
The secret has been changed.
> [_]: fix/make-the-jwt-expire-always

- src/app/routes/storage.ts
- src/app/services/folder.js
Checks folder tree ownership explicitly.
> [WT-87]: fix/check-folder-tree-ownership

- package.json
- src/app/routes/storage.ts
- src/app/services/folder.js
- src/config/initializers/redis.ts
Changes needed to connect to ovh:
- upgrade the ioRedis version to use the URI.
- change the lua script to ts to not use the "eval" command
⚠️  Removed environment variable REDIS_HOST and REDIS_PASSWORD in favor of REDIS_CONNECTION_STRING
> [DT-3]Feat/changes redis to ovh

- bin/delete-files/Dockerfile
- bin/delete-files/index.ts
- Adds dockerfile
- Fixes types
> [_]: fix/delete-files

- src/app/routes/gateway.js
- src/app/services/files.js
Allows to check the existence of a file by its `fileId` (the id from the network) via gateway
> [_]: feat/gateway-file-check

- src/app/routes/storage.ts
Log error messages when a file deletion fails.
> [_]: fix/log-errors-on-file-deletion

- src/app/services/user.js
Limits the times an email can be sent to verify a user email.
> [WT-269] fix: limit email verification

- migrations/20230104183916-extend-mail-limit-enum.js
- src/app/models/mailLimit.ts
Extends the `mail_type` enum on the `mail_limits` table to allow establishing new limits.
> [_]: fix/extend-email-verification-enum

- migrations/20230105113000-modify-index-folder-plain-name.js
- src/app/services/folder.js
- src/config/environments/sequelize.js
- Modified folders_plainname_parentid_key index to not collide with Trash elements
> [_]: feat/modified-folders-table-plain_name-index

- src/app/models/file.ts
- src/app/models/folder.ts
- src/app/services/files.js
- src/app/services/folder.js
These changes aim to introduce UUIDs to all storage-relate actions: files, folders and their relations.
> [_]: feat/integrate-uuid-on-storage

- src/app/services/folder.js
Fixes a weird, hidden bug when checking parent folder existence on folder creation.
> [_]: fix/where-condition-on-folder-creation

- src/app/services/user.js
Limits the times an email can be sent to deactivate a user email.
> [WT-270] fix: limit user deactivation email by the user email to deactivate

- migrations/20230303133000-add-deactivateUser-to-mailType-enum.js
- src/app/models/mailLimit.ts
- src/app/services/user.js
- Added migration with the alter type SQL
- Added deactivateUser to mailType enum
- Used exported enum instead of literal strings
> [_]: Feat/Add deactivateUser to mailType enum

- src/config/initializers/database.ts
- src/config/initializers/server.ts
These changes aim to enable database connection pool configuration by environment variables
> [_]: feat/configure-db-connection-by-env

- src/app/routes/storage.ts
- src/app/services/files.js
Changes: 
- Detailed errors when a file creation fails.
- Refactored file creation codebase
> [_]: refactor/create-file

- migrations/20230302120000-rename-mailType-enum.js
- migrations/20230303133000-add-deactivateUser-to-mailType-enum.js
- Added migration to rename mailType enum
- Added sequelize down to deactivateUser mailType migration
> [WT-345]: Fix/Rename mail type enum

- infrastructure/docker-compose.yml
- package.json
- src/app/middleware/analytics.ts
- src/app/routes/auth.ts
- src/app/routes/plan.js
- src/config/environments/development.js
- src/lib/analytics/AnalyticsService.ts
- yarn.lock
Fixes multiple errors that were making the development environment crash randomly: 
- Analytics service not handling async errors
- Missing HOST parameter for non-clustered local database
- Listing a plan from an individual was returning the Stripe HTTP error code response directly
> [_]: fix/dev-env

- src/app/routes/storage.ts
- src/config/initializers/notifications.ts
- Added UUID to notification when create a file
> [PB-206] : fix(notifications): send notification of the file created using the UUID

- src/app/services/folder.js
- Update deleted field to true when delete a folder
- Update deletedAt with date when delete a folder
> [PB-640]   bugfix/Error deleting backups

- src/app/services/user.js
- Changed default field to defaults to set the default values correctly
> [PB-434]: bugfix/delete-account-mails-default-daily-limit

- src/app/models/file.ts
- src/app/services/files.js
- Added status field to file model
- Changed status field to EXISTS when move a file in order to restore correctly when restore a file from trash
> [PB-719]: bugfix/change status to exists when move deleted file

- src/app/routes/storage.ts
- src/config/initializers/notifications.ts
> [PB-718] feature/Add email and uuid to socket emit events

- bin/delete-files/index.ts
- bin/delete-files/utils.ts
- src/app/models/file.ts
- tsconfig.json
Command to handle file deletion considering the new way of marking a file as deleted
> [PB-467]: feat/background-deletion

- src/app/routes/auth.ts
> [PB-755]: bugfix/Send to client correct http error and no generic one

- src/app/routes/auth.ts
- src/app/services/user.js
- tests/controllers/auth.test.ts
- tests/e2e/e2e-spec.ts
- Changed 'Wrong email/password' error message for 'Wrong login credentials'
> [_]: feature/Changed error message when email or password is wrong

- src/app/middleware/resource-sharing.middleware.ts
- src/app/models/index.ts
- src/app/models/permissions.ts
- src/app/models/privateSharingFolder.ts
- src/app/models/privateSharingFolderRole.ts
- src/app/models/roles.ts
- src/app/routes/storage.ts
- src/app/services/privateSharing.js
- src/lib/performance/network.ts
Changes: 
- Add middleware to apply resources access permissions in case the requester tries to access to those resources
> [PB-118]: Feat/middleware private sharing

- src/app/models/index.ts
- src/app/models/permissions.ts
- src/app/models/roles.ts
- src/app/models/sharingInvites.ts
- src/app/models/sharingRoles.ts
- src/app/models/sharings.ts
- src/app/services/privateSharing.js
Changes: 
- Use new models to allow more extensible sharing features
> [PB-118]: feat/advanced sharing

- src/app/routes/storage.ts
Add the email to the log so we can identify the user facing the issue
> [_]: Add info of the user that is creating a file if it fails

- .github/workflows/e2e-tests.yml
- .github/workflows/run-tests.yml
- Dockerfile
- package.json
- yarn.lock
These changes aim to: 
- Add the new relic setup to start collecting APM data
- Upgrade the Node.js version to 16
> [_]: feat/install-newrelic-apm

- src/app/routes/gateway.js
- src/app/services/featureLimit.js
Free tier is applied by default if passed planId is not valid
> fix: gateway update tier does not fail anymore

- src/app/services/folder.js
- Added condition to get only existing files and folders
> [_]: bugfix/Added condition to get only existing files and folders

- src/app/routes/backup.js
This PR adds a log to view the backups device update payload
> [_]:(fix) Add log to view device update payload for backups

- src/app/models/file.ts
- src/app/services/files.js
- Adds new creationTime column at files table (useful value for desktop apps)
- Removes modification of created_at value when creating a new file
> [_]: feat/add-creationTime-files-column

- src/app/services/folder.js
It adds a check to block the creation of folders with parent id set to null
> [_]: fix/remove-create-folders-with-no-parent-id 

- src/app/services/files.js
- Removed the use of encrypted names when searching for files
> [_]: feat/change-encrypted-name-to-plain-name
